import { Data } from './interfaces.tsx';

export const data: Data = {
  countries: [
    { id: 1, name: 'Россия', coordinates: [56.010548, 92.852571] },
    { id: 2, name: 'Беларусь', coordinates: [53.527989205539754, 28.046241929555535] },
  ],
  cities: [
    { id: 1, name: 'Екатеринбург', countryId: 1 },
    { id: 2, name: 'Тюмень', countryId: 1 },
    { id: 3, name: 'Минск', countryId: 2 },
    { id: 4, name: 'Гродно', countryId: 2 },
  ],
  offices: [
    // Офисы в Екатеринбурге
    {
      id: 1,
      cityId: 1,
      cityName: 'Екатеринбург',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 1 Екатеринбург',
      phone: ['+73431234567'],
      email: 'office1ekb@example.com',
      coordinates: [56.8389, 60.6057],
      owner: 'Иван Иванов',
    },
    {
      id: 2,
      cityId: 1,
      cityName: 'Екатеринбург',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 2 Екатеринбург',
      phone: ['+73437654321'],
      email: 'office2ekb@example.com',
      coordinates: [56.8519, 60.6122],
      owner: 'Петр Петров',
    },
    {
      id: 3,
      cityId: 1,
      cityName: 'Екатеринбург',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 3 Екатеринбург',
      phone: ['+73439876543'],
      email: 'office3ekb@example.com',
      coordinates: [56.8406, 60.6148],
      owner: 'Алексей Алексеев',
    },
    {
      id: 4,
      cityId: 1,
      cityName: 'Екатеринбург',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 4 Екатеринбург',
      phone: ['+73431231234'],
      email: 'office4ekb@example.com',
      coordinates: [56.8434, 60.6048],
      owner: 'Сергей Сергеев',
    },
    // Офисы в Тюмени
    {
      id: 5,
      cityId: 2,
      cityName: 'Тюмень',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 1 Тюмень',
      phone: ['+73452512345'],
      email: 'office1tym@example.com',
      coordinates: [57.1522, 65.5272],
      owner: 'Николай Николаев',
    },
    {
      id: 6,
      cityId: 2,
      cityName: 'Тюмень',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 2 Тюмень',
      phone: ['+73452554321'],
      email: 'office2tym@example.com',
      coordinates: [57.1613, 65.5188],
      owner: 'Владимир Владимиров',
    },
    {
      id: 7,
      cityId: 2,
      cityName: 'Тюмень',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 3 Тюмень',
      phone: ['+73452765432'],
      email: 'office3tym@example.com',
      coordinates: [57.153, 65.5346],
      owner: 'Дмитрий Дмитриев',
    },
    {
      id: 8,
      cityId: 2,
      cityName: 'Тюмень',
      countryId: 1,
      countryName: 'Россия',
      name: 'Офис 4 Тюмень',
      phone: ['+73452987654'],
      email: 'office4tym@example.com',
      coordinates: [57.1468, 65.5418],
      owner: 'Андрей Андреев',
    },
    // Офисы в Минске
    {
      id: 9,
      cityId: 3,
      cityName: 'Минск',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 1 Минск',
      phone: ['+375291234567'],
      email: 'office1minsk@example.com',
      coordinates: [53.9022, 27.5618],
      owner: 'Олег Олегов',
    },
    {
      id: 10,
      cityId: 3,
      cityName: 'Минск',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 2 Минск',
      phone: ['+375297654321'],
      email: 'office2minsk@example.com',
      coordinates: [53.9061, 27.5547],
      owner: 'Артём Артёмов',
    },
    {
      id: 11,
      cityId: 3,
      cityName: 'Минск',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 3 Минск',
      phone: ['+375299876543'],
      email: 'office3minsk@example.com',
      coordinates: [53.91, 27.5619],
      owner: 'Кирилл Кириллов',
    },
    {
      id: 12,
      cityId: 3,
      cityName: 'Минск',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 4 Минск',
      phone: ['+375293123456'],
      email: 'office4minsk@example.com',
      coordinates: [53.9096, 27.5774],
      owner: 'Максим Максимов',
    },
    // Офисы в Гродно
    {
      id: 13,
      cityId: 4,
      cityName: 'Гродно',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 1 Гродно',
      phone: ['+375152345678'],
      email: 'office1gro@example.com',
      coordinates: [53.6784, 23.8295],
      owner: 'Виктор Викторов',
    },
    {
      id: 14,
      cityId: 4,
      cityName: 'Гродно',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 2 Гродно',
      phone: ['+375157654321'],
      email: 'office2gro@example.com',
      coordinates: [53.6885, 23.8225],
      owner: 'Игорь Игорев',
    },
    {
      id: 15,
      cityId: 4,
      cityName: 'Гродно',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 3 Гродно',
      phone: ['+375159876543'],
      email: 'office3gro@example.com',
      coordinates: [53.6834, 23.8364],
      owner: 'Станислав Станиславов',
    },
    {
      id: 16,
      cityId: 4,
      cityName: 'Гродно',
      countryId: 2,
      countryName: 'Беларусь',
      name: 'Офис 4 Гродно',
      phone: ['+375153123456'],
      email: 'office4gro@example.com',
      coordinates: [53.6923, 23.8485],
      owner: 'Александр Александров',
    },
  ],
};
